### ISSUE TITLE
加入该项目申请

### ISSUE THREAD

**Issue by yujianFresh** [zhaohaihao/tourist-lovers-sns#1]
嗨，你好。我对这个主题很感兴趣，下班or周末可以一起开发，不知道能不能成为该项目的一员？

**Comment by zhaohaihao** [comment]
嗨，你好。首先感谢你的关注。当然是可以的，只不过目前我还在思考要做成什么样子，如果有兴趣的话可以留下即时通讯方式方便一起交流开发哦。

**Comment by yujianFresh** [comment]
加我微信呗,15811373668

**Comment by yujianFresh** [comment]
大兄弟周末ｏｒ晚上搞起来啊
